/**
 * PixAI Tagger v1.0 的**分类专属中文名**（NEXT 新增）。
 *
 * 为什么需要单独一张表：现有的 `zh_names.csv`（23,799 行）是从 Danbooru 通用/角色标签
 * 生成的，**完全不覆盖** `copyright`（作品系列）、`meta`（元信息）、`style`（画风）——
 * 实测 `blue_archive` / `highres` / `official_art` 在它里面一个都查不到。
 * 换模型之后这三类是**新增维度**，不补中文的话侧边栏就是一片英文。
 *
 * 三类各自的处理策略（2026-10 与用户确认）：
 *   · `copyright` 作品系列 —— **补中文**（`blue_archive` → 蔚蓝档案）。本表覆盖
 *     库里实际出现过的 + 常见系列；查不到的仍按现有行为显示英文原名，**不硬造**。
 *   · `meta` 元信息 —— **整类补全**（145 个全在表里；`unfinished` 之类原本就在
 *     `zh_names.csv` 里的会被这张表覆盖成更准确的说法）。
 *   · `style` 画风 —— **保持画师原名**（`tyomimas` / `bkub` 这些是画师账号名，
 *     翻译反而是错的）。所以这里**故意不提供** style 表。
 *   · `rating` 分级 —— 4 个短表放在 `pixai-tagger.ts` 里（与落库逻辑在一起）。
 *
 * ⚠️ 查找链的键是「标签英文原名」，与分类无关的标签**不会**被误翻；
 *    调用方按分类取对应的表（见 `pixaiChineseName(tagName, category)`）。
 */

import type { PixaiCategoryName } from "./pixai-tag-categories";

/** 元信息（145 个，与 `config.json` 的 meta 区间一一对应）。 */
export const PIXAI_META_ZH: Record<string, string> = {
  "acrylic_paint_(medium)": "丙烯（媒介）",
  "adoptable": "可领养角色",
  "adversarial_noise": "对抗噪声",
  "ai-assisted": "AI 辅助",
  "ai-generated": "AI 生成",
  "aliasing": "锯齿",
  "album_cover_redraw": "专辑封面重绘",
  "alpha_transparency": "带透明通道",
  "alt_text": "替代文本",
  "alternate_language": "其他语言版本",
  "animated": "动图",
  "animated_gif": "动画 GIF",
  "annotated": "带标注",
  "art_study": "练习作",
  "art_trade": "交换画",
  "artbook": "画集",
  "artist_collaboration": "画师合作",
  "absurdres": "超高分辨率",
  "ballpoint_pen_(medium)": "圆珠笔（媒介）",
  "blender_(medium)": "Blender（媒介）",
  "calligraphy_brush_(medium)": "毛笔（媒介）",
  "check_artist": "待校对画师",
  "check_character": "待校对角色",
  "check_clothing": "待校对服装",
  "check_copyright": "待校对作品",
  "check_translation": "待校对翻译",
  "clip_studio_paint_(medium)": "Clip Studio Paint（媒介）",
  "colored_pencil_(medium)": "彩铅（媒介）",
  "colorized": "已上色",
  "comic_panel_redraw": "漫画分镜重绘",
  "completion_time": "完成时长",
  "concept_art": "概念图",
  "contest_winner": "比赛获奖",
  "corrupted_metadata": "元数据损坏",
  "corrupted_twitter_file": "推特文件损坏",
  "cosplay_photo": "Cosplay 照片",
  "countdown_illustration": "倒计时插画",
  "crease": "折痕",
  "cropped": "已裁剪",
  "decensored": "去码版",
  "derivative_work": "二次创作",
  "detexted": "去字版",
  "downscaled": "已缩小",
  "duplicate": "重复图",
  "end_card": "片尾卡",
  "exif_rotation": "EXIF 旋转",
  "eyecatch": "过场图",
  "fancy_embedded_notes": "内嵌花式注释",
  "fanfiction_available": "有同人小说",
  "figure_(medium)": "手办（媒介）",
  "figure-referenced": "参考手办",
  "figure_available": "有手办",
  "game_asset": "游戏素材",
  "game_model": "游戏模型",
  "game_screenshot": "游戏截图",
  "gift_art": "赠图",
  "gimp_(medium)": "GIMP（媒介）",
  "graphite_(medium)": "铅笔（石墨）",
  "guest_art": "客串画",
  "headshop": "头部贴图素材",
  "highres": "高分辨率",
  "ibispaint_(medium)": "ibisPaint（媒介）",
  "inactive_account": "账号已注销",
  "incredibly_absurdres": "极其超高分辨率",
  "ink_(medium)": "墨水（媒介）",
  "jpeg_artifacts": "JPEG 压缩伪影",
  "key_visual": "主视觉图",
  "koikatsu_(medium)": "Koikatsu（媒介）",
  "krita_(medium)": "Krita（媒介）",
  "looping_animation": "循环动画",
  "lossy-lossless": "有损转无损",
  "lowres": "低分辨率",
  "magazine_scan": "杂志扫描",
  "making-of": "制作花絮",
  "making-of_available": "有制作花絮",
  "marker_(medium)": "马克笔（媒介）",
  "masking_tape_(medium)": "美纹纸（媒介）",
  "md5_mismatch": "MD5 不一致",
  "merchandise_available": "有周边",
  "microsoft_paint_(medium)": "画图（媒介）",
  "mikumikudance_(medium)": "MikuMikuDance（媒介）",
  "millipen_(medium)": "针管笔（媒介）",
  "mixed_media": "混合媒介",
  "mousepad_(medium)": "鼠标垫（媒介）",
  "nib_pen_(medium)": "蘸水笔（媒介）",
  "novel_illustration": "小说插图",
  "nude_filter": "裸体滤镜",
  "off-topic": "脱离主题",
  "official_art": "官方图",
  "official_artist_extra": "官方画师加笔",
  "official_wallpaper": "官方壁纸",
  "oil_painting_(medium)": "油画（媒介）",
  "paint.net_(medium)": "Paint.NET（媒介）",
  "paint_chat_(medium)": "PaintChat（媒介）",
  "painting_(medium)": "绘画（媒介）",
  "painttool_sai_(medium)": "PaintTool SAI（媒介）",
  "papercraft_(medium)": "纸艺（媒介）",
  "partially_annotated": "部分标注",
  "pastel_(medium)": "粉彩（媒介）",
  "pdf_available": "有 PDF",
  "pen_(medium)": "钢笔（媒介）",
  "photo-referenced": "参考照片",
  "photo_(medium)": "照片（媒介）",
  "photoshop_(medium)": "Photoshop（媒介）",
  "pixel-perfect_duplicate": "像素级重复",
  "procreate_(medium)": "Procreate（媒介）",
  "production_art": "制作资料",
  "promotional_art": "宣传图",
  "protected_link": "受保护链接",
  "psd_available": "有 PSD",
  "redrawn": "重绘",
  "resolution_mismatch": "分辨率不一致",
  "resized": "已缩放",
  "reverse_translation": "反向翻译",
  "rotated": "已旋转",
  "scan": "扫描",
  "scan_artifacts": "扫描伪影",
  "screenshot": "截图",
  "screenshot_redraw": "截图重绘",
  "self-datamine": "自行拆包",
  "self-portrait": "自画像",
  "spine_(medium)": "Spine（媒介）",
  "spoilers": "剧透",
  "stitched": "拼接图",
  "tagme": "待补充标签",
  "tall_image": "竖长图",
  "tegaki_draw_and_tweet": "手绘投稿（Tegaki）",
  "textless_version": "无字版",
  "third-party_edit": "第三方修改",
  "third-party_extraction": "第三方提取",
  "third-party_watermark": "第三方水印",
  "thumbnail_collage": "缩略图拼贴",
  "traditional_media": "传统媒介",
  "unconventional_media": "非常规媒介",
  "unfinished": "未完成",
  "upscaled": "已放大",
  "vector_trace": "矢量描摹",
  "video_thumbnail": "视频缩略图",
  "visual_novel_cg": "视觉小说 CG",
  "voice_drama_available": "有广播剧",
  "waifu2x": "waifu2x 放大",
  "watercolor_(medium)": "水彩（媒介）",
  "watercolor_pencil_(medium)": "水彩铅笔（媒介）",
  "wide_image": "横宽图",
};

/**
 * 作品系列（copyright）常见条目。
 *
 * ⚠️ 键必须与 `config.json` 里的 **Danbooru 标签原名逐字一致**（下划线/冒号/感叹号都要对），
 *    否则查找链匹配不上就退回英文原名（不会出错，只是没中文）。
 *    本表刻意只收「确定对得上」的常见系列；查不到的一律保持英文。
 */
export const PIXAI_COPYRIGHT_ZH: Record<string, string> = {
  "original": "原创",
  // ── 库里实际出现过的（按照片数）───────────────────────────────
  "blue_archive": "蔚蓝档案",
  "indie_virtual_youtuber": "独立虚拟主播",
  "arknights": "明日方舟",
  "gochuumon_wa_usagi_desu_ka?": "请问您今天要来点兔子吗？",
  "honkai_(series)": "崩坏系列",
  "honkai:_star_rail": "崩坏：星穹铁道",
  "nijisanji": "彩虹社",
  "flower_knight_girl": "花骑士",
  "nekopara": "猫娘乐园",
  "pokemon": "宝可梦",
  "idolmaster": "偶像大师",
  "vocaloid": "VOCALOID",
  "azur_lane": "碧蓝航线",
  "idolmaster_cinderella_girls": "偶像大师 灰姑娘女孩",
  "elsword": "艾尔之光",
  "the_legend_of_luo_xiaohei": "罗小黑战记",
  "virtuareal": "VirtuaReal",
  // ── 常见游戏 ──────────────────────────────────────────────
  "genshin_impact": "原神",
  "honkai_impact_3rd": "崩坏3",
  "honkai:_star_rail_(series)": "崩坏：星穹铁道",
  "zenless_zone_zero": "绝区零",
  "girls'_frontline": "少女前线",
  "girls'_frontline_2": "少女前线2：追放",
  "kantai_collection": "舰队Collection",
  "granblue_fantasy": "碧蓝幻想",
  "umamusume": "赛马娘",
  "princess_connect!": "公主连结Re:Dive",
  "nikke": "胜利女神：妮姬",
  "punishing:_gray_raven": "战双帕弥什",
  "counter:side": "异界事务所",
  "project_sekai": "世界计划 多彩舞台",
  "bang_dream!": "BanG Dream！",
  "love_live!": "LoveLive！",
  "love_live!_sunshine!!": "LoveLive！Sunshine！！",
  "love_live!_superstar!!": "LoveLive！Superstar！！",
  "love_live!_nijigasaki_high_school_idol_club": "LoveLive！虹咲学园",
  "the_idolmaster_shiny_colors": "偶像大师 闪耀色彩",
  "the_idolmaster_million_live!": "偶像大师 百万现场",
  "the_idolmaster_sidem": "偶像大师 SideM",
  "fate/grand_order": "Fate/Grand Order",
  "fate_(series)": "Fate 系列",
  "fate/stay_night": "Fate/stay night",
  "tsukihime": "月姬",
  "mahou_shoujo_madoka_magica": "魔法少女小圆",
  "touhou": "东方Project",
  "touhou_project": "东方Project",
  "girls_band_cry": "少女乐队哭泣",
  "nier:_automata": "尼尔：机械纪元",
  "nier_(series)": "尼尔系列",
  "persona_5": "女神异闻录5",
  "persona_3": "女神异闻录3",
  "persona_4": "女神异闻录4",
  "persona_(series)": "女神异闻录系列",
  "final_fantasy_vii": "最终幻想VII",
  "final_fantasy_xiv": "最终幻想XIV",
  "final_fantasy_(series)": "最终幻想系列",
  "the_legend_of_zelda": "塞尔达传说",
  "the_legend_of_zelda:_breath_of_the_wild": "塞尔达传说 旷野之息",
  "super_mario": "超级马力欧",
  "sonic_the_hedgehog": "索尼克",
  "splatoon": "斯普拉遁",
  "fire_emblem": "火焰之纹章",
  "fire_emblem:_three_houses": "火焰之纹章 风花雪月",
  "xenoblade_chronicles": "异度神剑",
  "street_fighter": "街头霸王",
  "tekken": "铁拳",
  "king_of_fighters": "拳皇",
  "tales_of_(series)": "传说系列",
  "dragon_quest": "勇者斗恶龙",
  "monster_hunter": "怪物猎人",
  "resident_evil": "生化危机",
  "devil_may_cry": "鬼泣",
  "metal_gear": "合金装备",
  "silent_hill": "寂静岭",
  "bloodborne": "血源诅咒",
  "dark_souls": "黑暗之魂",
  "elden_ring": "艾尔登法环",
  "overwatch": "守望先锋",
  "league_of_legends": "英雄联盟",
  "valorant": "无畏契约",
  "apex_legends": "Apex 英雄",
  "minecraft": "我的世界",
  "terraria": "泰拉瑞亚",
  "stardew_valley": "星露谷物语",
  "undertale": "传说之下",
  "deltarune": "三角符文",
  "hollow_knight": "空洞骑士",
  "celeste": "蔚蓝",
  "arknights:_endfield": "明日方舟：终末地",
  "wuthering_waves": "鸣潮",
  "tower_of_fantasy": "幻塔",
  "identity_v": "第五人格",
  "onmyoji": "阴阳师",
  "honkai:_star_rail_(game)": "崩坏：星穹铁道",
  // ── 常见动画 / 漫画 ────────────────────────────────────────
  "chainsaw_man": "电锯人",
  "kimetsu_no_yaiba": "鬼灭之刃",
  "jujutsu_kaisen": "咒术回战",
  "bocchi_the_rock!": "孤独摇滚！",
  "oshi_no_ko": "我推的孩子",
  "spy_x_family": "SPY×FAMILY",
  "shingeki_no_kyojin": "进击的巨人",
  "dungeon_meshi": "迷宫饭",
  "sword_art_online": "刀剑神域",
  "re:zero_kara_hajimeru_isekai_seikatsu": "Re:从零开始的异世界生活",
  "overlord_(maruyama)": "OVERLORD",
  "konosuba": "为美好的世界献上祝福！",
  "neon_genesis_evangelion": "新世纪福音战士",
  "bleach": "境·界",
  "naruto": "火影忍者",
  "one_piece": "海贼王",
  "dragon_ball": "龙珠",
  "hunter_x_hunter": "全职猎人",
  "fullmetal_alchemist": "钢之炼金术师",
  "steins;gate": "命运石之门",
  "code_geass": "叛逆的鲁鲁修",
  "gundam": "高达",
  "kaguya-sama_wa_kokurasetai": "辉夜大小姐想让我告白",
  "kobayashi-san_chi_no_maid_dragon": "小林家的龙女仆",
  "yuru_camp": "摇曳露营△",
  "non_non_biyori": "悠哉日常大王",
  "k-on!": "轻音少女",
  "hibike!_euphonium": "吹响！上低音号",
  "violet_evergarden": "紫罗兰永恒花园",
  "made_in_abyss": "来自深渊",
  "houseki_no_kuni": "宝石之国",
  "yakusoku_no_neverland": "约定的梦幻岛",
  "yakitori": "烤鸡",
  "oshi_no_ko_(anime)": "我推的孩子",
  "sono_bisque_doll_wa_koi_wo_suru": "更衣人偶坠入爱河",
  "lycoris_recoil": "莉可丽丝",
  "tensei_shitara_slime_datta_ken": "关于我转生变成史莱姆这档事",
  "mushoku_tensei": "无职转生",
  "tate_no_yuusha_no_nariagari": "盾之勇者成名录",
  "spy_kyoushitsu": "间谍教室",
  "kimi_no_na_wa.": "你的名字。",
  "tenki_no_ko": "天气之子",
  "suzume_no_tojimari": "铃芽之旅",
  "mononoke_hime": "幽灵公主",
  "sen_to_chihiro_no_kamikakushi": "千与千寻",
  "howl_no_ugoku_shiro": "哈尔的移动城堡",
  "tonari_no_totoro": "龙猫",
  // ── 虚拟主播 / 其他 ───────────────────────────────────────
  "hololive": "hololive",
  "holostars": "HOLOSTARS",
  "nijisanji_en": "彩虹社 EN",
  "vspo!": "VSPO！",
  "kizuna_ai": "绊爱",
  "kamitsubaki_studio": "神椿工作室",
  "vsinger": "VSinger",
  "bilibili": "哔哩哔哩",
  "nanashi_inc.": "七次元",
  "vocaloid_(series)": "VOCALOID",
  "utau": "UTAU",
  "cevio": "CeVIO",
  "synthv": "Synthesizer V",
  "touken_ranbu": "刀剑乱舞",
  "twisted-wonderland": "迪士尼扭曲仙境",
  "ensemble_stars!": "偶像梦幻祭",
  "hypnosis_mic": "催眠麦克风",
  "idolish7": "IDOLiSH7",
  "a3!": "A3！",
  "bang_dream!_girls_band_party!": "BanG Dream！少女乐团派对",
  "d4dj": "D4DJ",
  "princess_principal": "Princess Principal",
  "yuri!!!_on_ice": "冰上的尤里",
  "haikyuu!!": "排球少年！！",
  "kuroko_no_basket": "黑子的篮球",
  "free!": "Free！",
  "given": "GIVEN",
  "banana_fish": "Banana Fish",
  "doukyuusei": "同级生",
  "umineko_no_naku_koro_ni": "海猫鸣泣之时",
  "higurashi_no_naku_koro_ni": "寒蝉鸣泣之时",
  "clannad": "CLANNAD",
  "air_(visual_novel)": "AIR",
  "kanon": "Kanon",
  "little_busters!": "Little Busters！",
  "angel_beats!": "Angel Beats！",
  "charlotte_(anime)": "Charlotte",
  "yuru_yuri": "摇曳百合",
  "gochuumon_wa_usagi_desu_ka?_(series)": "请问您今天要来点兔子吗？",
  "new_game!": "NEW GAME！",
  "blend_s": "Blend S",
  "slow_start": "Slow Start",
  "comic_girls": "Comic Girls",
  "hanayamata": "花舞少女",
  "sansha_sanyou": "三者三叶",
  "kiniro_mosaic": "黄金拼图",
  "ga_ge_ga": "搞姬日常",
  "anima_yell!": "Anima Yell！",
  "wataten!": "天使降临到了我身边！",
  "machikado_mazoku": "街角魔族",
  "urara_meirochou": "乌拉拉迷路帖",
  "yuyushiki": "悠悠式",
  "ichigo_mashimaro": "草莓棉花糖",
  "azumanga_daioh": "阿滋漫画大王",
  "lucky_star": "幸运星",
  "hidamari_sketch": "向阳素描",
  "nichijou": "日常",
  "kill_me_baby": "Kill Me Baby",
  "sabagebu!": "生存游戏社",
  "gabriel_dropout": "废天使加百列",
  "himouto!_umaru-chan": "干物妹！小埋",
  "himouto!_umaru-chan_r": "干物妹！小埋R",
  "kobayashi-san_chi_no_maid_dragon_s": "小林家的龙女仆S",
  "maid_dragon": "小林家的龙女仆",
};

/**
 * 按分类取中文名。返回 `null` 表示"这张表里没有"，调用方继续往下找
 * （`zh_names.csv` → 英文原名）。
 *
 * ⚠️ `style`（画风）**故意永远返回 null** —— 那些是画师账号名，保持原名才对。
 */
export function pixaiChineseName(
  tagName: string,
  category: PixaiCategoryName
): string | null {
  if (category === "copyright") {
    return PIXAI_COPYRIGHT_ZH[tagName] ?? null;
  }
  if (category === "meta") {
    return PIXAI_META_ZH[tagName] ?? null;
  }
  // style / general / character / rating 都没有分类专属表：
  // general/character 走既有的 zh_names.csv，rating 走 pixai-tagger.ts 里的 4 条短表。
  return null;
}

/** 表里各有多少条（启动时打一行日志，方便核对覆盖面）。 */
export function pixaiChineseNameCoverage(): {
  copyright: number;
  meta: number;
} {
  return {
    copyright: Object.keys(PIXAI_COPYRIGHT_ZH).length,
    meta: Object.keys(PIXAI_META_ZH).length,
  };
}
