/**
 * WD14 通用标签的类型划分（自用新增）。
 *
 * 为什么需要：WD14 有 8,106 个通用标签，实测全库跑完预计 5,000–7,500 个会有命中。
 * 侧边栏若平铺这么多标签会卡死，所以按类型折成二级目录。
 *
 * ⚠️ 模型文件里**没有**现成的类型映射（`selected_tags.csv` 只区分 general/character/rating；
 * `tags_info.csv` 只有别名与两个布尔），所以这里用**关键词/后缀规则**分类。
 * 规则覆盖率的量化验证见 `_research/measure_tag_categories.cjs`。
 *
 * 规则**按顺序匹配，先命中先定**：越具体的规则要放越前面
 * （例如 `hair_ornament` 属于服装配饰，而 `long_hair` 属于头发）。
 */

export interface Wd14TagCategory {
  /** 稳定 id，用于落库到父标签的映射与测试 */
  id: string;
  /** 侧边栏显示名 */
  label: string;
}

export const WD14_TAG_CATEGORIES: Wd14TagCategory[] = [
  { id: "meta", label: "元信息与画质" },
  { id: "style", label: "画风与媒介" },
  { id: "composition", label: "人数与构图" },
  { id: "hair", label: "头发" },
  { id: "face", label: "面部与表情" },
  { id: "body", label: "身体与特征" },
  { id: "clothing", label: "服装与配饰" },
  { id: "pose", label: "动作与姿势" },
  { id: "scene", label: "场景与背景" },
  { id: "creature", label: "动物与植物" },
  { id: "object", label: "物体与道具" },
  { id: "explicit", label: "成人向内容" },
  { id: "other", label: "其他" },
];

/** 精确匹配集合（这些名字用规则不好表达，直接列出）。 */
const EXACT: Record<string, string[]> = {
  meta: [
    "highres",
    "absurdres",
    "lowres",
    "watermark",
    "signature",
    "artist_name",
    "commentary",
    "commentary_request",
    "dated",
    "english_text",
    "translated",
    "translation_request",
    "bad_id",
    "bad_pixiv_id",
    "bad_twitter_id",
    "bad_deviantart_id",
    "bad_link",
    "bad_source",
    "twitter_username",
    "web_address",
    "copyright_request",
    "character_request",
    "artist_request",
    "sample_watermark",
    "text_focus",
    "speech_bubble",
    "thought_bubble",
    "dialogue",
    "censored",
    "bar_censor",
    "mosaic_censoring",
    "uncensored",
    "third_party_edit",
    "official_art",
    "scan",
    "jpeg_artifacts",
    "blurry",
    "depth_of_field",
    "motion_blur",
    "chromatic_aberration",
    "film_grain",
    "vignetting",
    "lens_flare",
    "light_particles",
  ],
  style: [
    "monochrome",
    "greyscale",
    "sketch",
    "watercolor",
    "lineart",
    "comic",
    "chibi",
    "realistic",
    "traditional_media",
    "pixel_art",
    "flat_color",
    "screencap",
    "vector_trace",
    "ink",
    "oil_painting",
    "pastel_colors",
    "limited_palette",
    "colorful",
    "spot_color",
    "cel_shading",
    "soft_shading",
    "gradient",
    "halftone",
    "dithering",
    "stippling",
    "hatching_(texture)",
    "cross-hatching",
    "rough_sketch",
    "unfinished",
    "sketchbook",
    "doodle",
    "manga",
    "4koma",
    "doujinshi",
    "album_cover",
    "movie_poster",
    "card_(medium)",
    "sticker",
    "key_visual",
    "official_alternate_costume",
  ],
  composition: [
    "solo",
    "solo_focus",
    "duo",
    "trio",
    "group",
    "1girl",
    "2girls",
    "3girls",
    "4girls",
    "5girls",
    "6+girls",
    "multiple_girls",
    "1boy",
    "2boys",
    "3boys",
    "4boys",
    "5boys",
    "6+boys",
    "multiple_boys",
    "male_focus",
    "female_focus",
    "close-up",
    "portrait",
    "full_body",
    "upper_body",
    "lower_body",
    "cowboy_shot",
    "wide_shot",
    "pov",
    "third-person_pov",
    "first-person_pov",
    "perspective",
    "vanishing_point",
    "foreshortening",
    "wide_angle",
    "fisheye",
    "symmetry",
    "centered",
    "off-center",
    "rule_of_thirds",
    "negative_space",
    "border",
    "letterboxed",
    "pillarboxed",
    "out_of_frame",
    "head_out_of_frame",
    "feet_out_of_frame",
    "cropped_legs",
    "cropped_torso",
    "cropped_arms",
    "cropped_head",
    "character_doll",
    "multiple_views",
    "reference_sheet",
    "turnaround",
    "expression_chart",
    "collage",
    "grid",
    "split_screen",
  ],
  body: [
    "wings",
    "tail",
    "multiple_tails",
    "animal_ears",
    "cat_ears",
    "dog_ears",
    "fox_ears",
    "rabbit_ears",
    "wolf_ears",
    "mouse_ears",
    "bear_ears",
    "horse_ears",
    "pointy_ears",
    "elf",
    "horns",
    "halo",
    "fang",
    "fangs",
    "heterochromia",
    "colored_sclera",
    "slit_pupils",
    "heart-shaped_pupils",
    "symbol-shaped_pupils",
    "glowing_eyes",
    "sparkle",
    "sparkles",
    "aura",
    "glowing",
    "tattoo",
    "scar",
    "bandaid",
    "mole_under_eye",
    "freckles",
    "blush",
    "sweatdrop",
    "tears",
    "snot",
    "drooling",
    "saliva",
    "navel",
    "midriff",
    "collarbone",
    "cleavage",
    "underboob",
    "sideboob",
    "covered_nipples",
    "pectorals",
    "abs",
    "toned",
    "muscular",
    "chubby",
    "fat",
    "slim",
    "curvy",
    "wide_hips",
    "thick_thighs",
    "thigh_gap",
    "long_legs",
    "bare_shoulders",
    "bare_legs",
    "bare_arms",
    "bare_feet",
    "barefoot",
    "toes",
    "fingers",
    "nail_polish",
    "pale_skin",
    "dark_skin",
    "tan",
    "tanlines",
    "suntan",
    "skin_fang",
    "fur",
    "feathers",
    "scales",
    "fin",
    "horn",
    "antenna_hair",
    "ahoge",
  ],
  pose: [
    "standing",
    "sitting",
    "kneeling",
    "squatting",
    "crouching",
    "lying",
    "on_back",
    "on_stomach",
    "on_side",
    "prone",
    "supine",
    "walking",
    "running",
    "jumping",
    "flying",
    "falling",
    "dancing",
    "singing",
    "sleeping",
    "stretching",
    "bent_over",
    "bending",
    "leaning_forward",
    "leaning_back",
    "arms_up",
    "arms_behind_back",
    "arms_behind_head",
    "arms_crossed",
    "arms_at_sides",
    "hand_on_hip",
    "hand_up",
    "hand_on_own_chest",
    "hands_on_hips",
    "hands_up",
    "hands_behind_back",
    "holding",
    "hugging",
    "hug",
    "carrying",
    "eating",
    "drinking",
    "reading",
    "writing",
    "cooking",
    "fighting",
    "slouching",
    "legs_crossed",
    "crossed_legs",
    "crossed_arms",
    "crossed_ankles",
    "spread_legs",
    "knees_up",
    "knees_together",
    "legs_up",
    "legs_apart",
    "foot_up",
    "tiptoes",
    "outstretched_arm",
    "outstretched_arms",
    "outstretched_leg",
    "outstretched_hand",
    "reaching",
    "reaching_towards_viewer",
    "waving",
    "salute",
    "peace_sign",
    "v_sign",
    "thumbs_up",
    "pointing",
    "pointing_at_viewer",
    "presenting",
    "covering_face",
    "covering_mouth",
    "covering_eyes",
    "hands_on_own_face",
    "head_tilt",
    "turning_head",
    "bowing",
    "curtsy",
    "crawling",
    "riding",
    "on_bed",
    "on_floor",
    "against_wall",
    "sitting_on_*",
  ],
  scene: [
    "simple_background",
    "white_background",
    "black_background",
    "grey_background",
    "blue_background",
    "red_background",
    "green_background",
    "pink_background",
    "yellow_background",
    "purple_background",
    "orange_background",
    "brown_background",
    "two-tone_background",
    "gradient_background",
    "transparent_background",
    "colored_background",
    "checkered_background",
    "polka_dot_background",
    "striped_background",
    "floral_background",
    "indoors",
    "outdoors",
    "sky",
    "blue_sky",
    "cloudy_sky",
    "night_sky",
    "starry_sky",
    "clouds",
    "cloud",
    "sun",
    "sunlight",
    "sunset",
    "sunrise",
    "moon",
    "full_moon",
    "stars",
    "night",
    "day",
    "evening",
    "morning",
    "rain",
    "raining",
    "snow",
    "snowing",
    "fog",
    "mist",
    "wind",
    "rainbow",
    "lightning",
    "tree",
    "trees",
    "forest",
    "grass",
    "grassland",
    "flower",
    "flowers",
    "flower_field",
    "petals",
    "falling_petals",
    "leaf",
    "leaves",
    "bamboo",
    "mountain",
    "mountains",
    "hill",
    "cliff",
    "beach",
    "ocean",
    "sea",
    "lake",
    "river",
    "waterfall",
    "underwater",
    "city",
    "cityscape",
    "skyline",
    "building",
    "buildings",
    "street",
    "road",
    "alley",
    "ruins",
    "space",
    "earth_(planet)",
    "classroom",
    "school",
    "library",
    "bedroom",
    "bed",
    "kitchen",
    "bathroom",
    "living_room",
    "dining_room",
    "office",
    "cafe",
    "restaurant",
    "bar_(place)",
    "shop",
    "storefront",
    "street_lamp",
    "window",
    "curtains",
    "mirror",
    "door",
    "wall",
    "floor",
    "ceiling",
    "stairs",
    "fence",
    "bridge",
    "pool",
    "swimming_pool",
    "onsen",
    "bath",
    "shower",
    "garden",
    "park",
    "shrine",
    "temple",
    "castle",
    "church",
    "tower",
    "school_uniform",
  ],
  object: [
    "sword",
    "weapon",
    "gun",
    "knife",
    "dagger",
    "spear",
    "bow_(weapon)",
    "arrow_(projectile)",
    "shield",
    "staff",
    "wand",
    "scythe",
    "axe",
    "hammer",
    "whip",
    "chain",
    "book",
    "notebook",
    "paper",
    "letter",
    "envelope",
    "pen",
    "pencil",
    "brush",
    "palette",
    "camera",
    "phone",
    "cellphone",
    "smartphone",
    "computer",
    "laptop",
    "keyboard_(computer)",
    "mouse_(computer)",
    "television",
    "headphones",
    "microphone",
    "speaker",
    "clock",
    "watch",
    "wristwatch",
    "umbrella",
    "bag",
    "handbag",
    "backpack",
    "box",
    "cardboard_box",
    "bottle",
    "cup",
    "mug",
    "glass",
    "teacup",
    "teapot",
    "plate",
    "bowl",
    "chopsticks",
    "spoon",
    "fork",
    "food",
    "cake",
    "ice_cream",
    "candy",
    "chocolate",
    "cookie",
    "bread",
    "rice",
    "fruit",
    "apple",
    "orange_(fruit)",
    "strawberry",
    "watermelon",
    "banana",
    "drink",
    "tea",
    "coffee",
    "juice",
    "wine",
    "beer",
    "balloon",
    "ribbon",
    "confetti",
    "gift",
    "present",
    "christmas_tree",
    "candle",
    "lantern",
    "lamp",
    "chandelier",
    "ball",
    "toy",
    "doll",
    "stuffed_animal",
    "plush",
    "blanket",
    "pillow",
    "towel",
    "chair",
    "table",
    "desk",
    "sofa",
    "bicycle",
    "car",
    "train",
    "airplane",
    "boat",
    "ship",
    "motorcycle",
    "crown",
    "trophy",
    "medal",
    "key",
    "chain",
    "syringe",
    "bandage",
    "medicine",
    "broom",
    "bucket",
    "basket",
    "ladder",
    "rope",
    "net",
    "balloon",
    "pinwheel",
    "wind_chime",
    "fireworks",
    "sparkler",
    "music",
    "musical_note",
    "sheet_music",
    "guitar",
    "piano",
    "violin",
    "drum",
    "flute",
  ],
};

/** 顺序敏感的正则规则：先命中先定。 */
const PATTERN_RULES: { id: string; patterns: RegExp[] }[] = [
  // ── 成人向内容（放最前：这些词形很独特，被别的规则吃掉会很难看）────
  {
    id: "explicit",
    patterns: [
      /^(sex|hetero|yuri|yaoi|bisexual|lesbian|gay|incest|netorare|ntr|rape|molestation|voyeurism|exhibitionism)$/,
      /(vaginal|anal|penetration|fellatio|cunnilingus|handjob|paizuri|masturbation|orgasm|ejaculation|precum|cumshot|cum_|_cum|semen|^cum$|^oral$|group_sex|fucked|penetrated)/,
      /(penis|pussy|vagina|anus|clitoris|urethra|testicles|scrotum|pubic_hair|groin|cameltoe|areola|nipples?)/,
      /(sex_toy|dildo|vibrator|onahole|condom|bondage|bdsm|shibari|restrained|bound_wrists|blindfold|collar_and_leash)/,
      /(ahegao|naughty_face|seductive_smile|orgasm_face|fucked_silly|impregnation|pregnant|birth)/,
      /(nude|naked|topless|bottomless|undressing|undressed|completely_nude|partially_nude)/,
      /(erection|bulge|crotch|inner_thigh|thigh_sex|breast_squeeze|nipple_|_nipple)/,
      /(panties_aside|clothing_aside|clothes_lift|clothing_cutout|see-through|transparent_clothing|wet_clothes|nipple_slip|wardrobe_malfunction)/,
      /(censored|uncensored|bar_censor|mosaic_censoring)$/,
    ],
  },
  // ── 元信息 / 画质 / 水印（要在最前，避免被别的规则吃掉）──────────
  {
    id: "meta",
    patterns: [
      /_(id|username|request|commentary|bubble|artifacts)$/,
      /^(bad_|sample_|third_party_|official_)/,
      /^(web_address|twitter_username|artist_name|commentary)/,
      /watermark/,
      /(highres|lowres|absurdres|huge_filesize)$/,
      /_(text|font|logo)$/,
      /^(translated|translation|english_text|chinese_text|japanese_text)/,
      /^(character_name|copyright_name|series_name|virtual_youtuber|cosplay|original|spoilers?)$/,
      /^(no_humans|commentary_request|translation_request)$/,
    ],
  },
  // ── 服装配饰：含 hair_ornament / hair_bow 等，必须排在"头发"之前 ──
  {
    id: "clothing",
    patterns: [
      /hair_(ornament|band|bow|clip|flower|ribbon|scrunchie|bobbles?)/,
      /(dress|skirt|shirt|blouse|sweater|cardigan|hoodie|jacket|coat|cloak|cape|vest|suit|tuxedo|uniform|kimono|yukata|hakama|sailor|serafuku|maid|apron|nurse|santa|witch|miko|swimsuit|bikini|one-piece|leotard|bodysuit|wetsuit|diving_suit|tracksuit|jersey|armor|plate_armor|chainmail|robe|gown|qipao|cheongsam|hanbok|sari)/,
      /(bra|panties|underwear|lingerie|boxers|briefs|thong|garter|stockings|pantyhose|tights|socks|thighhighs|legwear|kneehighs|fishnet|leg_warmer|leg_garter)/,
      /(gloves|mittens|gauntlets|arm_warmers|bracelet|bangle|wristband|cuffs|ring|necklace|pendant|choker|earrings|earring|piercing|brooch|lapel_pin)/,
      /(hat|cap|beret|beanie|helmet|hood|crown|tiara|headband|headphones|veil|scarf|neckerchief|bandana|mask|eyepatch|blindfold)/,
      /(shoes|boots|sandals|slippers|heels|pumps|loafers|sneakers|geta|zouri|footwear)/,
      /(necktie|bowtie|bow_tie|ascot|ribbon|bow|sash|belt|buckle|suspender|button|zipper|lace|frills|pleated|fur_trim|trim)/,
      /(backpack|handbag|shoulder_bag|satchel|purse|wallet|pouch|holster|scabbard|sheath)/,
      /(swimsuit|bikini|school_swimsuit|competition_swimsuit|sports_swimsuit)/,
      /(sleeves?|sleeveless|sleeves_past|detached_sleeves|puffy_sleeves|wide_sleeves|long_sleeves|short_sleeves)/,
      /(collar|turtleneck|strapless|off_shoulder|halter|tube_top|crop_top|highleg|zettai_ryouiki|bare_shoulders)/,
      /(plaid|checkered|striped|polka_dot|argyle|houndstooth|paisley|floral_print|_print$|pattern)/,
      /(pants|shorts|jeans|trousers|leggings|bloomers|petticoat|corset|bustier|sarong|wrap_skirt)/,
      /(jewelry|necklace|choker|bracelet|earring|brooch|tiara|hairpin|barrette|bell|badge|armband|epaulettes|insignia|medal|bib)/,
      /_(uniform|outfit|costume|wear|clothes|clothing)$/,
      /^(clothed|nude|topless|bottomless|partially_clothed|undressing|dressing)/,
    ],
  },
  // ── 头发 ─────────────────────────────────────────────────────
  {
    id: "hair",
    patterns: [
      /hair/,
      /^(twintails?|twin_tails|ponytail|side_ponytail|braid|braids|twin_braids|french_braid|bun|double_bun|hair_bun|bob_cut|hime_cut|ahoge|drill|drills|sidelocks|sidelock|bangs|swept_bangs|blunt_bangs|parted_bangs|antenna|regent|updo|cornrows|dreadlocks|afro|mohawk|crew_cut|undercut|bowl_cut|pompadour|mullet|pixie_cut|wavy|curly|straight|flipped|feathered|layered|messy|floating|wind_blown)/,
    ],
  },
  // ── 面部 / 表情 / 眼睛 ────────────────────────────────────────
  {
    id: "face",
    patterns: [
      /eyes?(_|$)/,
      /eyelash/,
      /eyebrow/,
      /_(eyes|pupils|sclera|eyelashes|eyebrows)$/,
      /^(glasses|sunglasses|goggles|monocle|scouter|visor|eyewear|makeup|lipstick|eyeshadow|mascara|blush|lip)/,
      /(smile|grin|frown|scowl|pout|smirk|open_mouth|closed_mouth|parted_lips|clenched_teeth|tongue|licking|lips|teeth|yawn|scream|shouting|laughing|crying|teary|tears|sobbing|angry|annoyed|surprised|shocked|embarrassed|flustered|confused|expressionless|emotionless|serious|determined|smug|seductive|naughty_face|ahegao|orgasm|wink|one_eye_closed|half-closed_eyes|closed_eyes|wide-eyed|empty_eyes|dead_eyes|sparkling_eyes|stare|glare|looking_)/,
      /(face|facial|forehead|nose|cheek|cheeks|chin|mouth|lip)/,
      /^(\^_\^|>_<|:3|:d|:p|:o|;\)|:\)|:\(|:\||v|x3|uwu|owo|<3)$/,
      /^(heart|star|sparkle|note|symbol|sweatdrop)$/,
    ],
  },
  // ── 姿势 / 动作 ──────────────────────────────────────────────
  {
    id: "pose",
    patterns: [
      /^(sitting|standing|kneeling|squatting|crouching|lying|walking|running|jumping|flying|falling|dancing|singing|sleeping|stretching|bending|leaning|slouching|bowing|curtsy|crawling|riding|floating|hovering|swimming|hanging|dangling)/,
      /^on_(back|stomach|side|bed|floor|ground|knees|tiptoes|one_knee|all_fours|top|bottom)/,
      /^(arms?|hands?|legs?|feet|foot|knees?|ankles?|fingers?|shoulders?|hips?|waist|torso|head)_/,
      /_(up|down|apart|together|crossed|raised|outstretched|behind|forward|backwards|bent)$/,
      /^(holding|hugging|carrying|eating|drinking|reading|writing|cooking|fighting|waving|salute|pointing|presenting|reaching|covering|touching|grabbing|pulling|pushing|throwing|catching|climbing|dancing)/,
      /^(peace_sign|v_sign|thumbs_up|ok_sign|heart_hands|middle_finger)/,
      /(hand_on_|hands_on_|arms_on_|legs_on_|sitting_on_|standing_on_|lying_on_)/,
      /(crossed_legs|crossed_arms|crossed_ankles|spread_legs|legs_crossed|arms_crossed|knees_up|knees_together|head_tilt|turning_head|bent_over|tiptoes)/,
      /^(:d|:o|:p|:3|;\)|:\)|:\(|:\||xd$)/,
    ],
  },
  // ── 身体特征 ─────────────────────────────────────────────────
  {
    id: "body",
    patterns: [
      /(breasts?|chest|nipples?|navel|midriff|cleavage|underboob|sideboob|pectorals|abs|groin|waist|hips?|stomach|belly|thighs?|butt|ass|flat_chest|collarbone)/,
      /^(breasts?|nipples?|areola|navel|midriff|collarbone|thighs?|legs?|arms?|hands?|fingers?|toes?|feet|foot|armpits?|soles?|back|skin|waist|hips?|stomach|belly|butt|ass)/,
      /(thigh_gap|wide_hips|narrow_waist|extra_ears|_girl$|loli|child|bara|otoko_no_ko|personification|humanization)/,
      /(sweat|sweatdrop|wet|dripping|drool|saliva|blood|bruise|injury|wound|bandage|bandaid)/,
      /(bare_(shoulders|legs|arms|feet|back|chest|midriff|stomach)|barefoot|topless|bottomless)/,
      /(animal_ears|cat_ears|dog_ears|fox_ears|rabbit_ears|wolf_ears|mouse_ears|bear_ears|horse_ears|pointy_ears|fake_animal_ears|animal_ear_fluff|animal_ear_headband)/,
      /(tail|tails|fox_tail|cat_tail|wolf_tail|horse_tail|multiple_tails|tail_ornament)/,
      /(wings|feathers|horns?|halo|antennae|fin|fins|scales|fur|fluff)/,
      /(heterochromia|slit_pupils|symbol-shaped_pupils|heart-shaped_pupils|colored_sclera|glowing_eyes)/,
      /(tattoo|scar|scarification|bandaid|bandage|mole|freckles|birthmark|piercing)/,
      /(skin|complexion|pale|tan|tanlines|suntan|dark_skin|dark-skinned)/,
      /(muscular|toned|abs|chubby|fat|slim|curvy|petite|tall|short|giant|tiny)/,
      /(nail_polish|fingernails|makeup)/,
      /(monster|creature|youkai|demon|angel|elf|dwarf|orc|mermaid|centaur|dragon|kitsune|nekomata)/,
    ],
  },
  // ── 动物与植物（必须在 scene 之前：rose / cat 等词形会被 scene 的宽规则吃掉）──
  {
    id: "creature",
    patterns: [
      /^(bird|cat|dog|fox|wolf|rabbit|bunny|mouse|rat|bear|horse|pony|deer|elk|cow|bull|pig|sheep|goat|monkey|ape|lion|tiger|leopard|cheetah|panther|elephant|giraffe|zebra|panda|koala|squirrel|hedgehog|raccoon|otter|beaver|seal|walrus|dolphin|whale|shark|fish|octopus|squid|jellyfish|crab|shrimp|lobster|snail|frog|toad|snake|lizard|turtle|tortoise|crocodile|dinosaur|dragon|penguin|owl|eagle|hawk|falcon|crow|raven|sparrow|swan|duck|goose|chicken|rooster|peacock|flamingo|parrot|insect|butterfly|moth|bee|wasp|ant|spider|scorpion|beetle|mosquito|worm|caterpillar|unicorn|pegasus|phoenix|griffin|mermaid|slime|goblin|orc|fairy|angel|devil|demon|ghost|zombie|skeleton|vampire|werewolf|kitsune|nekomata|tanuki|kappa)$/,
      /_(animal|bird|cat|dog|fox|wolf|rabbit|bear|horse|fish|dragon|snake|insect|butterfly)$/,
      /(animal|creature|monster|pokemon|dinosaur)/,
      /(rose|sunflower|tulip|cherry_blossom|sakura|maple_leaf|clover|dandelion|hydrangea|hibiscus|lavender|pansy|daisy|orchid|lotus|mushroom|fern|cactus|succulent|bonsai|ivy|wisteria)/,
    ],
  },
  // ── 场景 / 背景 ──────────────────────────────────────────────
  {
    id: "scene",
    patterns: [
      /_background$/,
      /^(simple|white|black|grey|gray|blue|red|green|pink|yellow|purple|orange|brown|transparent|colored|gradient|two-tone|checkered|polka_dot|striped|floral|heart)_/,
      /(sky|cloud|star|moon|sun|sunset|sunrise|rainbow|aurora|galaxy|nebula)/,
      /(night|day|evening|morning|dawn|dusk|noon|midnight)$/,
      /(rain|snow|fog|mist|wind|storm|thunder|lightning|blizzard)/,
      /^(indoors|outdoors|inside|outside)$/,
      /(tree|forest|grass|flower|petal|leaf|leaves|bamboo|plant|vine|moss|bush|hedge)/,
      /(mountain|hill|cliff|canyon|valley|desert|field|plain|meadow|prairie)/,
      /(beach|ocean|sea|wave|lake|river|pond|waterfall|underwater|coral|reef|shore|coast|harbor|pier|dock)/,
      /(city|cityscape|skyline|building|street|road|alley|town|village|rooftop|balcony|ruins|construction)/,
      /(room|classroom|library|bedroom|kitchen|bathroom|office|cafe|restaurant|shop|store|bar_|hall|corridor|hallway|entrance|attic|basement)/,
      /(window|curtain|mirror|door|wall|floor|ceiling|stairs|fence|bridge|gate|pillar|column|arch)/,
      /(pool|onsen|bath|shower|garden|park|shrine|temple|castle|church|tower|stadium|gym|hospital|station|airport)/,
      /(space|planet|earth|universe|void|abstract_background)/,
      /(season|spring|summer|autumn|fall|winter|cherry_blossoms|sakura|maple)/,
      /(water|ripple|reflection|shadow|silhouette|lighting|backlighting|rim_light|sunbeam|god_rays|light_rays|dappled_sunlight|caustics)/,
      /^(day|night|sunset|sunrise|horizon|landscape|scenery)$/,
    ],
  },
  // ── 画风 / 媒介 ──────────────────────────────────────────────
  {
    id: "style",
    patterns: [
      /^(monochrome|greyscale|grayscale|sepia|sketch|watercolor|lineart|line_art|comic|chibi|realistic|semi-realistic|traditional_media|pixel_art|flat_color|screencap|vector_trace|ink|oil_painting|pastel|limited_palette|colorful|spot_color|cel_shading|soft_shading|gradient|halftone|dithering|stippling|hatching|cross-hatching|rough_sketch|unfinished|sketchbook|doodle|manga|4koma|doujinshi|album_cover|movie_poster|sticker|key_visual|concept_art|illustration|anime|cartoon|3d|2d|cgi|render|photorealistic|photo)/,
      /_(medium|style|shading|palette|art)$/,
      /^(animated|animation|animated_gif|webm|video)$/,
      /^(solo_|group_|duo_)?(focus)$/,
    ],
  },
  // ── 人数 / 构图 / 视角 ───────────────────────────────────────
  {
    id: "composition",
    patterns: [
      /^\d+\+?(girl|boy|other)s?$/,
      /^(multiple_girls|multiple_boys|multiple_others|male_focus|female_focus|solo|solo_focus|duo|trio|group|everyone|crowd)$/,
      /^(from_(above|below|behind|side|outside|front)|looking_at_|looking_(down|up|back|away|to_the_side)|facing_)/,
      /(close-up|portrait|full_body|upper_body|lower_body|cowboy_shot|wide_shot|medium_shot|dutch_angle|pov|perspective|vanishing_point|foreshortening|wide_angle|fisheye|panorama)/,
      /(cropped|out_of_frame|partially_visible|head_out_of_frame|feet_out_of_frame)/,
      /(symmetry|centered|off-center|rule_of_thirds|negative_space|border|letterboxed|pillarboxed|framed)/,
      /(multiple_views|reference_sheet|turnaround|expression_chart|collage|grid|split_screen|comparison)/,
      /_(focus|shot|view|angle)$/,
    ],
  },
  // ── 补充兜底（放最后：只接住上面都没命中的长尾标签）────────────────
  // 这些是逐个看"落入其他"的样例后补出来的族，放在最后不影响前面更精确的判定。
  {
    id: "clothing",
    patterns: [
      /(playboy_bunny|headgear|obi|scrunchie|formal|casual|blazer|denim|kimono|yukata|apparel|outfit|attire|footwear|swimwear|lingerie|nightwear|sleepwear)/,
      /(clothes_pull|panty_pull|_pull$|pantyshot|clothing_|_clothing)/,
    ],
  },
  {
    id: "pose",
    patterns: [
      /(wariza|all_fours|straddling|girl_on_top|trembling|clenched_hand|kiss|hug|embrace|carried|piggyback|bridal_carry)/,
    ],
  },
  {
    id: "face",
    patterns: [/^(happy|sad|angry|;d|\?|\^\^\^|clenched_hand|kiss)$/],
  },
  {
    id: "object",
    patterns: [
      /(stuffed_toy|instrument|polearm|bed_sheet|gem|robot|bug|weapon|tool|furniture|vehicle|machinery)/,
    ],
  },
  {
    id: "meta",
    patterns: [/(parody|crossover|spoiler|meme|reference|inside_joke)/],
  },
  {
    id: "style",
    patterns: [
      /(motion_lines|speed_lines|steam|fire|smoke|crescent|effect|glow|bloom|bokeh)/,
    ],
  },
];

/**
 * 判断一个 WD14 通用标签属于哪个类型。
 *
 * @param name     WD14 标签名（英文 / 罗马字）
 * @param category WD14 的 category（0=general，4=character，9=rating）
 * @returns 分类 id（见 WD14_TAG_CATEGORIES）
 */
export function categorizeWd14Tag(name: string, category: number): string {
  if (category === 4) {
    return "character";
  }
  if (category === 9) {
    return "rating";
  }
  const lower = name.toLowerCase();

  for (const [id, names] of Object.entries(EXACT)) {
    if (names.includes(lower)) {
      return id;
    }
  }
  for (const rule of PATTERN_RULES) {
    for (const pattern of rule.patterns) {
      if (pattern.test(lower)) {
        return rule.id;
      }
    }
  }
  return "other";
}
